In [1]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/home/biba_bo/.local/lib/python3.6/site-packages/tensorflow/_api/v2/version/__init__.py'>


### Creating Tensors

In [3]:
string = tf.Variable('This is a string', tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

### Rank/Degree of Tensors

In [4]:
rank_1_tensor = tf.Variable(['test', 'ok', 'tim'], tf.string)
rank_2_tensor = tf.Variable([['test', 'ok'], ['test', 'yes']], tf.string)

In [8]:
tf.rank(rank_1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [9]:
tf.rank(rank_2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

### Tensor shape

In [10]:
rank_2_tensor.shape

TensorShape([2, 2])

### Changing tensor shape

In [11]:
tensor_1 = tf.ones([1, 2, 3])
tensor_2 = tf.reshape(tensor_1, [2, 3, 1])
tensor_3 = tf.reshape(tensor_2, [3, -1])    # -1 tells the tensor to calculate the size of the dimension in that place
                                            # this will reshape the tensor to [3, 2]

# !!! The number of elements in the reshaped tensor MUST match the number in the original

In [12]:
print(tensor_1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [13]:
print(tensor_2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [14]:
print(tensor_3)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


### Types of Tensors
* Variable
* Constant
* Placeholder
* SparseTensor

### Evaluating Tensors

In [15]:
with tf.Session() as sess:  # creates a session using the default graph
    tensor.eval()           # tensor will of course be the name of your tensor

AttributeError: module 'tensorflow' has no attribute 'Session'